import { Day6Pipe } from './day6.pipe';

describe('Day6Pipe', () => {
  it('should work for part 1', () => {
    const pipe = new Day6Pipe();
    expect(pipe.transform(`....#.....
    .........#
    ..........
    ..#.......
    .......#..
    ..........
    .#..^.....
    ........#.
    #.........
    ......#...`).part1).toEqual('41');
  });

  it('should work for part 2', () => {
    const pipe = new Day6Pipe();
    expect(pipe.transform(`....#.....
    .........#
    ..........
    ..#.......
    .......#..
    ..........
    .#..^.....
    ........#.
    #.........
    ......#...`).part2).toEqual('6');
  });
});
