import { Day8Pipe } from './day8.pipe';

describe('Day8Pipe', () => {
  const pipe = new Day8Pipe();
  
  describe('part 1', () => {
    it('finds anti-nodes within map', () => {
      expect(pipe.transform(`..........
..........
..........
....a.....
..........
.....a....
..........
..........
..........
..........`).part1).toEqual('2');
    });
    
    it('ignores anti-nodes outside map', () => {
      expect(pipe.transform(`..........
..........
....a.....
..........
..........
.....a....
..........
..........
..........
..........`).part1).toEqual('1');
    });

    it('finds antinodes from 3 antennas', () => {
      expect(pipe.transform(`..........
..........
..........
....a.....
........a.
.....a....
..........
..........
..........
..........`).part1).toEqual('4');
    });

    it('works with multiple frequencies and overlapping nodes', () => {
      expect(pipe.transform(`............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`).part1).toEqual('14');
    })
    
  });

  describe('part 2', () => {
    it('continues to search further out for antinodes', () => {
      expect(pipe.transform(`T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........`).part2).toEqual('9');
    });

    it('works with multiple frequencies and overlapping nodes', () => {
      expect(pipe.transform(`............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`).part2).toEqual('34');
    });
    
  })
});
